language: java
dist: bionic
jdk:
  - openjdk11
install:
  - ./mvnw clean
  - ./mvnw test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - ./mvnw test jacoco:report
after_success:
  - ./mvnw coveralls:report
